# Generated by Django 5.2.5 on 2025-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('fazer', 'Fazer'), ('fazendo', 'Fazendo'), ('concluido', 'Concluído')], default='fazer', max_length=10),
        ),
    ]
